### ISSUE TITLE
添加cookie和运行都是在哪里弄

### ISSUE THREAD

**Issue by ZHDreamer** [zhongfly/arknight2ndactivity#1]
添加cookie和运行都是在哪里弄，我现在把cookie手动添加到.py文件，然后手动运行也可以，但我想知道正确的打开方式

**Comment by zhongfly** [comment]
https://gist.github.com/zhongfly/149668fda6e205e5d3c1cde4637afcbc#file-arknight2ndactivity-py-L128
填在128行引号内
